# Source/Test directories
sonar.sources=src/main/frontend,src/main/java
sonar.tests=src/test/java

# Binaries
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Libraries
sonar.java.libraries=target/dependency/**/*.jar
sonar.java.test.libraries=target/dependency/**/*.jar

# Jacoco Coverage Report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
