@startuml
' Define classes
class User {
    - username : String
    - password : String
    - email : String
    - name : String
    - surname : String
    - roles : List<Userrole>
}

class Department {
  - name : String
  - startTime : DateTime
  - endTime : DateTime
}

class Absence {
    - start: DateTime
    - end: DateTime
    - recurrenceDaily : boolean
    - recurrenceWeekly: boolean
    - recurrenceMonthly: boolean
}

class ShiftPlan {
  - date : DateTime
  - state : State
}

class Shift {
  - startTime : DateTime
  - endTime : DateTime
}

enum Userrole {
  ADMIN
  MANAGER
  EMPLOYEE
}

enum State {
  DRAFT
  PUBLISHED
  CANCELLED
}

' Define relationships
Department "1..*" -- "1" User : manager
Department "0..*" -- "0..*" User : employees
Department "1" -- "0..*" ShiftPlan
ShiftPlan "1" -- "0..*" Shift
Shift "0..*" -- "0..*" User
Absence "0..*" -- "1" User


@enduml
