-- Insert users into USERX table
INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (1000, TRUE, 'Admin', 'Istrator', 'passwd', 'admin', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (2000, TRUE, 'Susi', 'Kaufgern', 'passwd', 'user1', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (3000, TRUE, 'Max', 'Mustermann', 'passwd', 'user2', 1000, '2024-01-01 00:00:00');

INSERT INTO USERX (ID, ENABLED, FIRST_NAME, LAST_NAME, PASSWORD, USERNAME, CREATE_USER_ID, CREATE_DATE) 
VALUES (4000, TRUE, 'Elvis', 'The King', 'passwd', 'elvis', 1000, '2024-01-01 00:00:00');

-- Insert roles into USERX_USERX_ROLE table by looking up the corresponding user ID
INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'admin'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'MANAGER');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user1'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'user2'), 'EMPLOYEE');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'ADMIN');

INSERT INTO USERX_USERX_ROLE (USERX_ID, ROLES) 
VALUES ((SELECT ID FROM USERX WHERE USERNAME = 'elvis'), 'EMPLOYEE');

--Insert Shiftplan into SHIFTPLAN table
INSERT INTO SHIFT_PLAN(ID)
VALUES (101);

-- Insert Shift into SHIFT table
INSERT INTO SHIFT(ID, START_TIME, END_TIME, SHIFTPLAN_ID)
VALUES (10001, '2025-01-02 00:08:00', '2025-01-02 00:16:00', 101);

INSERT INTO SHIFT(ID, START_TIME, END_TIME, SHIFTPLAN_ID, SHIFT_WORKER)
VALUES (20001, '2025-01-03 00:06:00', '2025-01-03 00:14:00', 101);


--shiftWorkers own table SHIFT_WORKERS, because ManyToMany
INSERT INTO SHIFT_WORKERS(SHIFT_ID, USER_ID)
VALUES (10001, 2000);

INSERT INTO SHIFT_WORKERS(SHIFT_ID, USER_ID)
VALUES (10001, 3000);

INSERT INTO SHIFT_WORKERS(SHIFT_ID, USER_ID)
VALUES (10001, 4000);

INSERT INTO SHIFT_WORKERS(SHIFT_ID, USER_ID)
VALUES (10001, 1000);

INSERT INTO SHIFT_WORKERS(SHIFT_ID, USER_ID)
VALUES (20001, 2000);